import { readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const dataRoot = join(root, 'src', 'data', 'reports', 'papers');
const generatedPath = join(root, 'src', 'generated-reports.ts');
const methodologyPath = join(root, 'src', 'data', 'methodology.json');
const generatedMethodologyPath = join(root, 'src', 'generated-methodology.ts');

/** @param {string} path */
async function readJson(path) {
	return JSON.parse(await readFile(path, 'utf8'));
}

let reports = [];
try {
	const index = await readJson(join(dataRoot, 'index.json'));
	if (!Array.isArray(index)) throw new Error('report index must be an array');
	for (const entry of index) {
		if (!entry || typeof entry.id !== 'string' || !/^[a-z0-9-]+$/.test(entry.id)) {
			throw new Error('report index contains an invalid id');
		}
		const report = await readJson(join(dataRoot, `${entry.id}.json`));
		if (report.id !== entry.id || report.source !== 'papers') {
			throw new Error(`report ${entry.id} does not match its index entry`);
		}
		reports.push(report);
	}
} catch (error) {
	const errorCode = error && typeof error === 'object' && 'code' in error ? error.code : undefined;
	if (errorCode !== 'ENOENT') throw error;
}

const source = `// Generated by scripts/sync-reports.mjs; do not edit.\nexport default ${JSON.stringify(reports)} as const;\n`;
await writeFile(generatedPath, source, 'utf8');
console.log(`Prepared ${reports.length} public report(s).`);

let methodology = {
	schemaVersion: 1,
	generatedAt: '',
	promptFingerprint: '',
	summaryPrompt: '',
	summaryInputTemplate: '',
};
try {
	const candidate = await readJson(methodologyPath);
	if (
		candidate?.schemaVersion === 1 &&
		typeof candidate.generatedAt === 'string' &&
		typeof candidate.promptFingerprint === 'string' &&
		typeof candidate.summaryPrompt === 'string' &&
		typeof candidate.summaryInputTemplate === 'string'
	) {
		methodology = candidate;
	} else {
		throw new Error('methodology data has an invalid shape');
	}
} catch (error) {
	const errorCode = error && typeof error === 'object' && 'code' in error ? error.code : undefined;
	if (errorCode !== 'ENOENT') throw error;
}
const methodologySource = `// Generated by scripts/sync-reports.mjs; do not edit.\nexport default ${JSON.stringify(methodology)} as const;\n`;
await writeFile(generatedMethodologyPath, methodologySource, 'utf8');
console.log(`Prepared public methodology (${methodology.summaryPrompt ? 'available' : 'unavailable'}).`);
