import { readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';

const root = resolve(import.meta.dirname, '..');
const dataRoot = join(root, 'src', 'data', 'reports', 'papers');
const generatedPath = join(root, 'src', 'generated-reports.ts');

/** @param {string} path */
async function readJson(path) {
	return JSON.parse(await readFile(path, 'utf8'));
}

let reports = [];
try {
	const index = await readJson(join(dataRoot, 'index.json'));
	if (!Array.isArray(index)) throw new Error('report index must be an array');
	for (const entry of index) {
		if (!entry || typeof entry.id !== 'string' || !/^[a-z0-9-]+$/.test(entry.id)) {
			throw new Error('report index contains an invalid id');
		}
		const report = await readJson(join(dataRoot, `${entry.id}.json`));
		if (report.id !== entry.id || report.source !== 'papers') {
			throw new Error(`report ${entry.id} does not match its index entry`);
		}
		reports.push(report);
	}
} catch (error) {
	const errorCode = error && typeof error === 'object' && 'code' in error ? error.code : undefined;
	if (errorCode !== 'ENOENT') throw error;
}

const source = `// Generated by scripts/sync-reports.mjs; do not edit.\nexport default ${JSON.stringify(reports)} as const;\n`;
await writeFile(generatedPath, source, 'utf8');
console.log(`Prepared ${reports.length} public report(s).`);
